### ISSUE TITLE
Logging in or registering crashes the app

### ISSUE THREAD

**Issue by ghost** [BeekeeperAlex/U413-archived#63]
/var/www/node_modules/mongoose-simpledb/node_modules/mongoose/node_modules/mquery/lib/utils.js:26
    if (/ObjectI[dD]$/.test(obj.constructor.name)) {
                       ^
RangeError: Maximum call stack size exceeded

**Comment by BeekeeperAlex** [comment]
This was caused by a change in [mongoose](http://mongoosejs.com/); it no longer automatically gets the ID of the document you pass in for a reference property so you have to explicitly pass in the document's `_id` property.

https://github.com/chevex/U413/commit/4aadffce0028c5ca52fc6cbf5712f4a32255f486
